### ISSUE TITLE
Failed to open source file

### ISSUE THREAD

**Issue by Domain** [hillin/FASTBuilder#5]
Sometimes I cannot click on the error message to open source file when setting external source editor to visual studio.
I wish I could debug it. But my development environment has no Internet access. The PC I am using now(which has Internet access) has no this problem. And the project dependency is complicate. If you can provide all third-party libraries to download, maybe I could have a try.

**Comment by hillin** [comment]
I've also encountered the problem when sometimes Visual Studio could not be found through the EnvDTE interface. But because it cannot be stably reproduced on my computer, the reason is unknown for now. I'm still trying to track it down.

The third party libraries can all be restored via Nuget. I'm attaching them here (under the MIT license), place the `packages` under the `Source` folder should do the trick:
[packages.zip](https://github.com/hillin/FASTBuild-Dashboard/files/1273574/packages.zip)

**Comment by Domain** [comment]
I have manage to debug this problem. That's because the initiatorProcessId is the id of cmd.exe, so it will never match the id of visual studio.

**Comment by hillin** [comment]
Could you take a look at the process inheritance tree (by using a tool like [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer))? Maybe in some scenarios we don't always have a Visual Studio as the ancestor process. A screenshot would be more helpful.

**Comment by hillin** [comment]
I read the code again and realized if Visual Studio is somehow started by another process (like `cmd.exe` in your situation), the initiator process will be that process in our current logic. This should be reconsidered, we should have a special rule set up for `devenv.exe` in the [GetRootProcessId](https://github.com/hillin/FASTBuild-Dashboard/blob/master/Source/ViewModels/Build/BuildInitiatorProcessViewModel.cs#L123) method.

**Comment by Domain** [comment]
Actually, in my situation, I use a bat file to call FBuild.exe directly. So the process tree has no visual studio at all. I think if you cannot find the vs in process tree, you can let the user to decide which vs to use, just like vsjitdebugger.

**Comment by hillin** [comment]
Implementing a vsjitdebugger-style instance selecting dialog is possible, but I think we'd better leave this as Plan B. There's better be an automatic way to choose which VS instance to use, otherwise it would be annoying if you have to choose by your self every time. 

Some approaches came in mind:
- Simply use the first VS instance found. Pros: easy to implement; Cons: may misbehave if multiple VS instances are running.
- Strict detection - try to traverse through the project tree of every VS instance, yield the first one which contains the file. As proved in a previous attempt, this is unacceptably slow, especially for large solutions.
- Pseudo-detection: try to find a VS instance whose solution file matches best with the file to open, location-wisely (i.e. `D:\project\source\test.sln` matches `D:\project\source\test\test.cpp` better than `E:\someplace\1.sln` or `D:\project\project.sln`). This could be decently fast, and will work well in most cases, unless you have some bizarrely structured projects.

**Comment by hillin** [comment]
I've improved the Visual Studio detection mechanism (in d60ef47f2e75c5c72716e9852b1f1c1f53f11505):

In priority order:

- An instance with matching initiator process ID
- An instance whose solution path matches the source file path best (pseudo owner detection)
- Any instance found
- Start a new instance
- Fallback to system default associated program
