### ISSUE TITLE
High CPU usage when there are many small tasks

### ISSUE THREAD

**Issue by ffulin** [hillin/FASTBuilder#8]
The overall CPU usage of the Dashboard seems to be pretty low (1-2%), but when FASTBuild is doing lots (hundreds) of very small tasks, I've seen the CPU usage increase significantly (25% and 40% on my 4 core/8 thread PC) for extended periods of time. Examples of "small tasks" include:
 - copying files (dependent dlls for example)
 - running Qt .moc generation

**Comment by hillin** [comment]
Hi, welcome here :)

When invalidating the render state of many jobs simultaneously (within a tick interval), it is possible that FBD consumes a large amount of CPU resources to preprocess them. This costs up to 10% on my i7-4790 processor. Because of the nature of invalidation, this shouldn't last long. 

Could you please provide a `FastBuildLog.log` file which reflects this issue?

**Comment by ffulin** [comment]
I'm really sorry for the slow reply. I am still hoping to find some time to create a good repro for you.

**Comment by hillin** [comment]
Close as stale.
